#include <pebble.h>

/* Message key values — must match "messageKeys" order in package.json.
 * Values are generated by the SDK into build/js/message_keys.json. */
#define MESSAGE_KEY_BG_COLOR      10000
#define MESSAGE_KEY_DIGIT_MODE    10001
#define MESSAGE_KEY_DIGIT_COLOR   10002
#define MESSAGE_KEY_TIME_24H      10003
#define MESSAGE_KEY_DIGIT_BG      10004
#define MESSAGE_KEY_BG_TYPE       10005

/* ── Geometry ─────────────────────────────────────────────────────────────── */
#define CELL        14    /* digit brick pixel size                           */
#define BG_CELL     10    /* background brick pixel size                      */
#define DIG_STUD     3    /* digit brick stud radius                          */
#define BG_STUD      2    /* background brick stud radius                     */
#define ANIM_MS     90    /* milliseconds between animation row reveals       */

/*
 * Horizontal layout (200 px wide, emery):
 *   3 + D(42) + 3 + D(42) + 3 + C(14) + 3 + D(42) + 3 + D(42) + 3 = 200
 */
#define DIG0_X    3
#define DIG1_X   48   /* 3 + 42 + 3                  */
#define COLON_X  93   /* 48 + 42 + 3, width = CELL   */
#define DIG2_X  110   /* 93 + 14 + 3                 */
#define DIG3_X  155   /* 110 + 42 + 3                */

/* Vertically centre the 70-px tall (5 × CELL) digit block: (228 - 70) / 2 */
#define TIME_Y   79

/* ── 3×5 digit bitmaps (bit 2 = left col, bit 0 = right col) ─────────────── */
/* Index 10 is a blank (all OFF) used for the suppressed leading zero in 12 h */
#define DIGIT_BLANK 10
static const uint8_t DIGIT_MAP[11][5] = {
    { 0b111, 0b101, 0b101, 0b101, 0b111 }, /* 0 */
    { 0b010, 0b110, 0b010, 0b010, 0b010 }, /* 1 */
    { 0b111, 0b001, 0b111, 0b100, 0b111 }, /* 2 */
    { 0b111, 0b001, 0b111, 0b001, 0b111 }, /* 3 */
    { 0b100, 0b101, 0b111, 0b001, 0b001 }, /* 4 */
    { 0b111, 0b100, 0b111, 0b001, 0b111 }, /* 5 */
    { 0b111, 0b100, 0b111, 0b101, 0b111 }, /* 6 */
    { 0b111, 0b001, 0b001, 0b001, 0b001 }, /* 7 */
    { 0b111, 0b101, 0b111, 0b101, 0b111 }, /* 8 */
    { 0b111, 0b101, 0b111, 0b001, 0b111 }, /* 9 */
    { 0b000, 0b000, 0b000, 0b000, 0b000 }, /* blank */
};

/* ── Settings ─────────────────────────────────────────────────────────────── */
#define PKEY_SETTINGS 0

typedef struct {
    int8_t bg_color;    /* 0 = random, 1-8 = solid LEGO colour, 9 = white   */
    int8_t digit_mode;  /* 0 = white, 1 = uniform colour, 2 = per-digit     */
    int8_t digit_color; /* colour index used when digit_mode == 1            */
                        /* 0 = white, 1-8 = LEGO colour                     */
    int8_t time_24h;    /* 0 = 12 h format, 1 = 24 h format (default)       */
    int8_t digit_bg;    /* OFF-brick fill: 0 = transparent, 1 = black,
                         * 2-9 = LEGO colours (red…purple)                  */
    int8_t bg_type;     /* 0 = brick pattern (default), 1 = uniform fill    */
} Settings;

static Settings s_settings;

/* ── Globals ──────────────────────────────────────────────────────────────── */
static Window   *s_window;
static Layer    *s_canvas;
static AppTimer *s_anim_timer;
static int       s_hours;
static int       s_minutes;
/* Per-digit: rows 0..s_anim_rows[d]-1 are visible; 5 = fully shown (static) */
static int       s_anim_rows[4];

/* ── Colour helpers ───────────────────────────────────────────────────────── */

/* Reduce each 2-bit channel by 1 (clamp at 0) for a darker shade. */
static GColor darken(GColor c) {
    GColor out;
    out.a = 3;
    out.r = c.r > 0 ? (uint8_t)(c.r - 1) : 0;
    out.g = c.g > 0 ? (uint8_t)(c.g - 1) : 0;
    out.b = c.b > 0 ? (uint8_t)(c.b - 1) : 0;
    return out;
}

/*
 * Eight classic LEGO colours (indices 0-7):
 *   0=Red  1=Blue  2=Yellow  3=Green  4=Orange  5=Cyan  6=Magenta  7=Purple
 */
static GColor lego_color(int idx) {
    static const uint8_t R[8] = { 255,   0, 255,   0, 255, 170,   0, 255 };
    static const uint8_t G[8] = {   0,  85, 255, 170,  85,   0, 170,   0 };
    static const uint8_t B[8] = {   0, 255,   0,   0,   0, 255, 170, 170 };
    int i = ((idx % 8) + 8) % 8;
    return GColorFromRGB(R[i], G[i], B[i]);
}

/* Resolve the background colour (ignoring brick vs uniform — that's in canvas). */
static GColor bg_solid_color(int col, int row) {
    if (s_settings.bg_color == 9) return GColorWhite;
    if (s_settings.bg_color == 0) {
        /* Random: vary by position for brick mode, vary by time for uniform */
        if (s_settings.bg_type == 1)
            return lego_color(s_hours % 8);
        return lego_color((col * 5) + (row * 7));
    }
    return lego_color(s_settings.bg_color - 1);
}

/*
 * ON-brick colour for digit position d (0-3):
 *   mode 0 → white
 *   mode 1 → uniform custom colour (digit_color index)
 *   mode 2 → per-digit: each position gets a distinct LEGO colour
 *             d=0 Red, d=1 Blue, d=2 Yellow, d=3 Green
 */
static GColor digit_on_color(int d) {
    switch (s_settings.digit_mode) {
        case 1:
            return s_settings.digit_color == 0
                   ? GColorWhite
                   : lego_color(s_settings.digit_color - 1);
        case 2:
            return lego_color(d);
        default:
            return GColorWhite;
    }
}

/*
 * OFF-brick fill colour for digit background:
 *   0 = transparent (skip drawing)  1 = black  2-9 = LEGO colours
 */
static GColor digit_off_color(void) {
    if (s_settings.digit_bg == 1) return GColorBlack;
    return lego_color(s_settings.digit_bg - 2);
}

/* ── Display helpers ──────────────────────────────────────────────────────── */

/*
 * Compute the four display digit values from s_hours / s_minutes and the
 * current time-format setting. Digit values are 0-9 or DIGIT_BLANK.
 * Called in both tick_handler (for change detection) and canvas_update_proc.
 */
static void get_display_digits(int digits[4]) {
    int h = s_hours;
    bool blank_leading = false;

    if (!s_settings.time_24h) {
        h = h % 12;
        if (h == 0) h = 12;
        blank_leading = (h < 10);   /* suppress leading zero: "9:05" not "09:05" */
    }

    digits[0] = blank_leading ? DIGIT_BLANK : h / 10;
    digits[1] = h % 10;
    digits[2] = s_minutes / 10;
    digits[3] = s_minutes % 10;
}

/* ── Drawing helpers ──────────────────────────────────────────────────────── */

static void draw_bg_brick(GContext *ctx, int x, int y) {
    GColor color = bg_solid_color(x / BG_CELL, y / BG_CELL);
    /* Body — 1 px gap at right/bottom creates the mortar-line grid effect */
    graphics_context_set_fill_color(ctx, color);
    graphics_fill_rect(ctx, GRect(x, y, BG_CELL - 1, BG_CELL - 1), 0, GCornerNone);
    /* Stud */
    GPoint c = GPoint(x + BG_CELL / 2 - 1, y + BG_CELL / 2 - 1);
    graphics_context_set_fill_color(ctx, darken(color));
    graphics_fill_circle(ctx, c, BG_STUD);
}

static void draw_digit_brick(GContext *ctx, int x, int y, GColor color) {
    /* Body with slight rounded corners for the LEGO plate look */
    graphics_context_set_fill_color(ctx, color);
    graphics_fill_rect(ctx, GRect(x, y, CELL - 1, CELL - 1), 2, GCornersAll);
    /* Stud */
    GPoint c = GPoint(x + CELL / 2 - 1, y + CELL / 2 - 1);
    graphics_context_set_fill_color(ctx, darken(color));
    graphics_fill_circle(ctx, c, DIG_STUD);
}

/* ── Canvas update ────────────────────────────────────────────────────────── */

static void canvas_update_proc(Layer *layer, GContext *ctx) {
    GRect bounds = layer_get_bounds(layer);

    /* 1 ── Background */
    if (s_settings.bg_type == 1) {
        /* Uniform fill — single flat colour, no brick pattern */
        graphics_context_set_fill_color(ctx, bg_solid_color(0, 0));
        graphics_fill_rect(ctx, bounds, 0, GCornerNone);
    } else {
        /* Brick pattern */
        for (int r = 0; r * BG_CELL < bounds.size.h; r++) {
            for (int c = 0; c * BG_CELL < bounds.size.w; c++) {
                draw_bg_brick(ctx, c * BG_CELL, r * BG_CELL);
            }
        }
    }

    /* 2 ── Time digits */
    const int DIG_X[4] = { DIG0_X, DIG1_X, DIG2_X, DIG3_X };
    int dv[4];
    get_display_digits(dv);

    for (int d = 0; d < 4; d++) {
        GColor on_color = digit_on_color(d);
        for (int row = 0; row < 5; row++) {
            if (row >= s_anim_rows[d]) break;
            for (int col = 0; col < 3; col++) {
                bool on = (DIGIT_MAP[dv[d]][row] >> (2 - col)) & 1;
                if (on) {
                    draw_digit_brick(ctx,
                        DIG_X[d] + col * CELL,
                        TIME_Y   + row * CELL,
                        on_color);
                } else if (s_settings.digit_bg != 0) {
                    draw_digit_brick(ctx,
                        DIG_X[d] + col * CELL,
                        TIME_Y   + row * CELL,
                        digit_off_color());
                }
                /* digit_bg == 0: transparent — background bricks show through */
            }
        }
    }

    /* 3 ── Colon: always visible (never changes) */
    draw_digit_brick(ctx, COLON_X, TIME_Y + 1 * CELL, GColorWhite);
    draw_digit_brick(ctx, COLON_X, TIME_Y + 3 * CELL, GColorWhite);
}

/* ── Animation timer ──────────────────────────────────────────────────────── */

static void anim_timer_cb(void *context) {
    s_anim_timer = NULL;
    bool still_animating = false;
    for (int d = 0; d < 4; d++) {
        if (s_anim_rows[d] < 5) {
            s_anim_rows[d]++;
            if (s_anim_rows[d] < 5) still_animating = true;
        }
    }
    layer_mark_dirty(s_canvas);
    if (still_animating) {
        s_anim_timer = app_timer_register(ANIM_MS, anim_timer_cb, NULL);
    }
}

/* ── Tick handler ─────────────────────────────────────────────────────────── */

static void tick_handler(struct tm *tick_time, TimeUnits units_changed) {
    /* Snapshot old display digits before updating time */
    int old_digits[4];
    get_display_digits(old_digits);

    s_hours   = tick_time->tm_hour;
    s_minutes = tick_time->tm_min;

    int new_digits[4];
    get_display_digits(new_digits);

    /* Only animate digits that actually changed */
    bool any_changed = false;
    for (int d = 0; d < 4; d++) {
        if (new_digits[d] != old_digits[d]) {
            s_anim_rows[d] = 0;
            any_changed = true;
        }
    }

    if (any_changed) {
        if (s_anim_timer) app_timer_cancel(s_anim_timer);
        layer_mark_dirty(s_canvas);
        s_anim_timer = app_timer_register(ANIM_MS, anim_timer_cb, NULL);
    }
}

/* ── AppMessage handler ───────────────────────────────────────────────────── */

static void inbox_received(DictionaryIterator *iter, void *ctx) {
    Tuple *t;

    /* select/radiogroup send string values ("0","1"…) → parse with atoi.
     * toggle sends an integer (0 or 1) → read as int32. */
    t = dict_find(iter, MESSAGE_KEY_BG_COLOR);
    if (t) s_settings.bg_color = (int8_t)(t->type == TUPLE_CSTRING
                                           ? atoi(t->value->cstring)
                                           : t->value->int32);

    t = dict_find(iter, MESSAGE_KEY_DIGIT_MODE);
    if (t) s_settings.digit_mode = (int8_t)(t->type == TUPLE_CSTRING
                                             ? atoi(t->value->cstring)
                                             : t->value->int32);

    t = dict_find(iter, MESSAGE_KEY_DIGIT_COLOR);
    if (t) s_settings.digit_color = (int8_t)(t->type == TUPLE_CSTRING
                                              ? atoi(t->value->cstring)
                                              : t->value->int32);

    t = dict_find(iter, MESSAGE_KEY_BG_TYPE);
    if (t) s_settings.bg_type = (int8_t)t->value->int32;

    t = dict_find(iter, MESSAGE_KEY_DIGIT_BG);
    if (t) s_settings.digit_bg = (int8_t)(t->type == TUPLE_CSTRING
                                           ? atoi(t->value->cstring)
                                           : t->value->int32);

    t = dict_find(iter, MESSAGE_KEY_TIME_24H);
    if (t) s_settings.time_24h = (int8_t)t->value->int32;

    persist_write_data(PKEY_SETTINGS, &s_settings, sizeof(Settings));
    layer_mark_dirty(s_canvas);
}

/* ── Settings load ────────────────────────────────────────────────────────── */

static void settings_load(void) {
    /* Defaults */
    s_settings.bg_color    = 0;   /* random      */
    s_settings.digit_mode  = 0;   /* white        */
    s_settings.digit_color = 0;   /* white        */
    s_settings.time_24h    = 1;   /* 24 h         */
    s_settings.digit_bg    = 0;   /* transparent  */
    s_settings.bg_type     = 0;   /* brick        */

    /* Overwrite with stored values if they exist */
    persist_read_data(PKEY_SETTINGS, &s_settings, sizeof(Settings));
}

/* ── Window handlers ──────────────────────────────────────────────────────── */

static void window_load(Window *window) {
    Layer *root   = window_get_root_layer(window);
    GRect  bounds = layer_get_bounds(root);

    s_canvas = layer_create(bounds);
    layer_set_update_proc(s_canvas, canvas_update_proc);
    layer_add_child(root, s_canvas);

    /* Show current time immediately with all rows visible */
    time_t    now = time(NULL);
    struct tm *t  = localtime(&now);
    s_hours       = t->tm_hour;
    s_minutes     = t->tm_min;
    for (int d = 0; d < 4; d++) s_anim_rows[d] = 5;
}

static void window_unload(Window *window) {
    if (s_anim_timer) {
        app_timer_cancel(s_anim_timer);
        s_anim_timer = NULL;
    }
    layer_destroy(s_canvas);
}

/* ── App lifecycle ────────────────────────────────────────────────────────── */

static void init(void) {
    settings_load();

    s_window = window_create();
    window_set_window_handlers(s_window, (WindowHandlers) {
        .load   = window_load,
        .unload = window_unload,
    });
    window_stack_push(s_window, true);

    app_message_register_inbox_received(inbox_received);
    app_message_open(256, 8);

    tick_timer_service_subscribe(MINUTE_UNIT, tick_handler);
}

static void deinit(void) {
    tick_timer_service_unsubscribe();
    app_message_deregister_callbacks();
    window_destroy(s_window);
}

int main(void) {
    init();
    app_event_loop();
    deinit();
}
